"""Run Capytaine BEM analysis for the Wigley hull and export BEMIO H5.

This script:
  1. Loads the Nemoh-format hull mesh generated by generate_meshes.py
  2. Configures a single FloatingBody in Capytaine
  3. Solves radiation and diffraction BEM problems
  4. Computes impulse response functions (radiation RIRF and excitation IRF)
  5. Writes the result in BEMIO HDF5 format for SEA-Stack

Dependencies:
    pip install capytaine numpy h5py scipy

Usage:
    python run_bem.py                 # full BEM solve, writes hydroData/wigley.h5
    python run_bem.py --quick         # reduced resolution for testing
    python run_bem.py --from-nc hydroData/wigley_capytaine.nc
    python run_bem.py --help
"""

from __future__ import annotations

import argparse
import math
import time
from pathlib import Path

import numpy as np
import h5py

try:
    import capytaine as cpt
except ImportError:
    raise ImportError(
        "Capytaine is required: pip install capytaine\n"
        "See https://capytaine.github.io/stable/user_manual/installation.html"
    )


# ---------------------------------------------------------------------------
# Wigley hull parameters (must match generate_meshes.py defaults)
# ---------------------------------------------------------------------------
LENGTH = 50.0
BEAM = 12.0
DRAFT = 3.5
FREEBOARD = 3.5
N_BODIES = 1
COG_Z = -1.75       # z-coordinate of CoG (approx -T/2)
RHO = 1025.0
G = 9.81
WATER_DEPTH = 250.0


# ---------------------------------------------------------------------------
# Body loading
# ---------------------------------------------------------------------------

def load_body(meshes_dir: Path, cog_z: float = COG_Z) -> cpt.FloatingBody:
    """Load the Nemoh mesh and configure the floating body.

    ``cog_z`` is the vertical centre-of-gravity (m, waterline at z=0). It sets
    the reference about which Capytaine computes the roll/pitch restoring
    stiffness, so it MUST match the model YAML ``com.location`` for a
    consistent hydrostatic equilibrium. Defaults to the shared 50 m hull value.
    """
    mesh_path = meshes_dir / "wigley.nemoh"
    if not mesh_path.exists():
        raise FileNotFoundError(
            f"Mesh not found: {mesh_path}\n"
            "Run generate_meshes.py first."
        )

    mesh = cpt.load_mesh(str(mesh_path), file_format="nemoh")
    body = cpt.FloatingBody(mesh=mesh)
    body.center_of_mass = np.array([0.0, 0.0, cog_z])
    body.rotation_center = np.array([0.0, 0.0, 0.0])
    body.add_all_rigid_body_dofs()
    body.keep_immersed_part()
    body.name = "wigley"
    print(f"  Loaded {body.name}: {body.mesh.nb_faces} wet panels, "
          f"center_of_mass={body.center_of_mass}")
    return body


def compute_body_hydrostatics(body: cpt.FloatingBody) -> dict:
    """Compute hydrostatic properties from the mesh."""
    hs = body.compute_hydrostatics(rho=RHO, g=G)
    C = np.array(hs["hydrostatic_stiffness"])
    dv = float(hs["disp_volume"])
    cb = np.array(hs["center_of_buoyancy"]).flatten()[:3]
    cg = np.asarray(body.center_of_mass, dtype=float).flatten()[:3]
    print(f"  {body.name}: V_disp={dv:.1f} m^3, cb_z={cb[2]:.3f} m, cg_z={cg[2]:.3f} m, "
          f"C33={C[2,2]:.0f} N/m, C44={C[3,3]:.0f} N-m/rad, C55={C[4,4]:.0f} N-m/rad")
    return {"stiffness": C, "disp_vol": dv, "cb": cb, "cg": cg}


# ---------------------------------------------------------------------------
# BEM solver
# ---------------------------------------------------------------------------

def solve_bem(
    body: cpt.FloatingBody,
    freq_range: np.ndarray,
    wave_directions: np.ndarray,
    n_jobs: int = 1,
) -> "xarray.Dataset":
    """Solve radiation and diffraction BEM problems."""
    import xarray as xr

    n_problems = len(freq_range) * (len(body.dofs) + len(wave_directions))
    print(f"\n  Body: {body.mesh.nb_faces} panels, {len(body.dofs)} DOFs")
    print(f"  Frequency range: {freq_range[0]:.3f} .. {freq_range[-1]:.3f} rad/s ({len(freq_range)} points)")
    print(f"  Wave directions: {np.degrees(wave_directions)} deg")
    print(f"  ~{n_problems} BEM problems to solve")

    if n_jobs != 1:
        try:
            import joblib  # noqa: F401
        except ImportError:
            print("  WARNING: joblib not installed -- falling back to sequential solve.")
            n_jobs = 1

    if n_jobs == 1:
        print("\n  Solving BEM problems sequentially...")
    elif n_jobs == -1:
        import os as _os
        print(f"\n  Solving BEM problems in parallel (all {_os.cpu_count()} cores)...")
    else:
        print(f"\n  Solving BEM problems in parallel ({n_jobs} workers)...")

    test_matrix = xr.Dataset({
        "omega": freq_range,
        "wave_direction": wave_directions,
        "radiating_dof": list(body.dofs),
        "water_depth": [WATER_DEPTH],
        "rho": [RHO],
    })

    solver = cpt.BEMSolver()
    t0 = time.time()
    dataset = solver.fill_dataset(test_matrix, body, n_jobs=n_jobs)
    elapsed = time.time() - t0
    print(f"  BEM solve completed in {elapsed:.1f} s")

    return dataset


# ---------------------------------------------------------------------------
# Impulse response functions (identical to 5SA run_bem.py)
# ---------------------------------------------------------------------------

def compute_radiation_irf(
    omega: np.ndarray,
    B: np.ndarray,
    t_end: float = 60.0,
    dt: float = 0.05,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute radiation IRF K(t) from damping B(omega).

    K(t) = (2/pi) * integral_0^inf B(omega) * cos(omega*t) d_omega
    """
    t = np.arange(0, t_end + dt / 2, dt)
    n_t = len(t)

    trailing = B.shape[1:]
    K = np.zeros(trailing + (n_t,))

    d_omega = np.gradient(omega)
    extra = (slice(None),) + (np.newaxis,) * len(trailing)
    for k in range(n_t):
        w = (np.cos(omega * t[k]) * d_omega)[extra]
        K[..., k] = (2.0 / math.pi) * np.sum(B * w, axis=0)

    return t, K


def compute_excitation_irf(
    omega: np.ndarray,
    F_re: np.ndarray,
    F_im: np.ndarray,
    t_end: float = 60.0,
    dt: float = 0.05,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute excitation IRF f(t) from complex excitation force.

    f(t) = (1/pi) * integral_0^inf [Re(F)*cos(wt) - Im(F)*sin(wt)] d_omega
    """
    t = np.arange(-t_end, t_end + dt / 2, dt)
    n_t = len(t)

    trailing = F_re.shape[1:]
    f = np.zeros(trailing + (n_t,))

    d_omega = np.gradient(omega)
    extra = (slice(None),) + (np.newaxis,) * len(trailing)
    for k in range(n_t):
        c = (np.cos(omega * t[k]) * d_omega)[extra]
        s = (np.sin(omega * t[k]) * d_omega)[extra]
        f[..., k] = (1.0 / math.pi) * np.sum(F_re * c - F_im * s, axis=0)

    return t, f


# ---------------------------------------------------------------------------
# BEMIO H5 writer (adapted from 5SA for single body)
# ---------------------------------------------------------------------------

def write_bemio_h5(
    output_path: Path,
    dataset: "xarray.Dataset",
    body_hydrostatics: dict | None = None,
    irf_t_end: float = 60.0,
    irf_dt: float = 0.05,
) -> None:
    """Convert Capytaine xarray Dataset to BEMIO H5 format for SEA-Stack."""
    rho = float(dataset.attrs.get("rho", RHO))
    g = G
    omega = dataset["omega"].values
    n_freq = len(omega)

    dof_names = list(dataset["radiating_dof"].values)
    n_dof = len(dof_names)

    wave_dirs = dataset["wave_direction"].values
    n_dir = len(wave_dirs)

    added_mass_full = dataset["added_mass"].values            # (n_freq, n_dof, n_dof)
    rad_damping_full = dataset["radiation_damping"].values     # (n_freq, n_dof, n_dof)

    Fk = dataset["Froude_Krylov_force"].values                # (n_freq, n_dir, n_dof) complex
    Fd = dataset["diffraction_force"].values                   # (n_freq, n_dir, n_dof) complex
    F_exc = Fk + Fd

    A_inf = added_mass_full[-1, :, :]

    print("  Computing radiation IRF...")
    rirf_t, rirf_K = compute_radiation_irf(omega, rad_damping_full,
                                           t_end=irf_t_end, dt=irf_dt)
    n_rirf_t = len(rirf_t)

    print("  Computing excitation IRF...")
    F_exc_re = np.real(F_exc)
    F_exc_im = np.imag(F_exc)
    exc_irf_t, exc_irf_f = compute_excitation_irf(omega, F_exc_re, F_exc_im,
                                                   t_end=irf_t_end, dt=irf_dt)
    n_exc_t = len(exc_irf_t)

    def _col(arr):
        return np.asarray(arr).reshape(-1, 1)

    def _scalar(v):
        return np.array([[float(v)]])

    print(f"  Writing BEMIO H5 to {output_path}")
    with h5py.File(str(output_path), "w") as f:
        sp = f.create_group("simulation_parameters")
        sp.create_dataset("rho", data=_scalar(rho))
        sp.create_dataset("g", data=_scalar(g))
        if np.isinf(WATER_DEPTH):
            sp.create_dataset("water_depth", data="infinite")
        else:
            sp.create_dataset("water_depth", data=_scalar(WATER_DEPTH))
        sp.create_dataset("w", data=_col(omega))
        sp.create_dataset("wave_dir", data=_col(np.degrees(wave_dirs)))

        bg = f.create_group("body1")
        props = bg.create_group("properties")

        if body_hydrostatics:
            bhs = body_hydrostatics
            disp_vol = bhs["disp_vol"]
            cb = bhs["cb"]
            C_body = bhs["stiffness"] / (rho * g)
            # Prefer the CoG actually used for the hydrostatics computation so
            # the written cg is consistent with the restoring stiffness.
            cg = bhs.get("cg", [0.0, 0.0, COG_Z])
        else:
            disp_vol = 4.0 * LENGTH * BEAM * DRAFT / 9.0
            cb = np.array([0.0, 0.0, -3.0 * DRAFT / 8.0])
            C_body = np.zeros((n_dof, n_dof))
            cg = [0.0, 0.0, COG_Z]

        props.create_dataset("disp_vol", data=_scalar(disp_vol))
        props.create_dataset("cg", data=_col(cg))
        props.create_dataset("cb", data=_col(cb))

        hc = bg.create_group("hydro_coeffs")
        hc.create_dataset("linear_restoring_stiffness", data=C_body)

        A_body = A_inf / rho
        am = hc.create_group("added_mass")
        am.create_dataset("inf_freq", data=A_body)

        K_body = rirf_K / rho
        rd = hc.create_group("radiation_damping")
        irf_group = rd.create_group("impulse_response_fun")
        irf_group.create_dataset("K", data=K_body)
        irf_group.create_dataset("t", data=_col(rirf_t))

        exc = hc.create_group("excitation")
        mag = np.abs(F_exc) / (rho * g)
        phase = np.angle(F_exc)
        exc.create_dataset("mag", data=np.transpose(mag, (2, 1, 0)))
        exc.create_dataset("phase", data=np.transpose(phase, (2, 1, 0)))

        f_body = exc_irf_f / (rho * g)
        exc_irf_group = exc.create_group("impulse_response_fun")
        exc_irf_group.create_dataset("f", data=np.transpose(f_body, (1, 0, 2)))
        exc_irf_group.create_dataset("t", data=_col(exc_irf_t))

    print(f"  BEMIO H5 written: {output_path}")
    print(f"    DOFs: {n_dof}")
    print(f"    Frequencies: {n_freq}, Wave directions: {n_dir}")
    print(f"    RIRF time steps: {n_rirf_t}, Excitation IRF time steps: {n_exc_t}")


# ---------------------------------------------------------------------------
# NetCDF checkpoint helpers
# ---------------------------------------------------------------------------

def _save_nc(dataset, nc_path: Path) -> None:
    from capytaine.io.xarray import separate_complex_values
    nc_path.parent.mkdir(parents=True, exist_ok=True)
    ds = separate_complex_values(dataset)
    for coord in ("radiating_dof", "influenced_dof"):
        if coord in ds.coords and hasattr(ds[coord].dtype, "categories"):
            ds[coord] = ds[coord].astype(str)
    ds.to_netcdf(
        str(nc_path),
        encoding={"radiating_dof": {"dtype": "U"}, "influenced_dof": {"dtype": "U"}},
    )
    print(f"  Capytaine NetCDF saved: {nc_path}")


def _load_nc(nc_path: Path):
    import xarray as xr
    from capytaine.io.xarray import merge_complex_values
    print(f"  Loading dataset from {nc_path} ...")
    return merge_complex_values(xr.open_dataset(str(nc_path)))


# ---------------------------------------------------------------------------
# Mesh visualization
# ---------------------------------------------------------------------------

def _plot_mesh_matplotlib(
    body: cpt.FloatingBody,
    title: str = "Wigley hull mesh",
) -> None:
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(14, 6))
    ax = fig.add_subplot(111, projection="3d")

    verts = body.mesh.vertices
    faces = body.mesh.faces

    polys = []
    for face in faces:
        poly = [verts[vi] for vi in face if vi < len(verts)]
        if len(poly) >= 3:
            polys.append(poly)

    collection = Poly3DCollection(
        polys, alpha=0.5, facecolor=(0.3, 0.3, 0.5),
        edgecolor=(0.2, 0.2, 0.2, 0.3), linewidth=0.3,
    )
    ax.add_collection3d(collection)

    margin = 5.0
    ax.set_xlim(verts[:, 0].min() - margin, verts[:, 0].max() + margin)
    ax.set_ylim(verts[:, 1].min() - margin, verts[:, 1].max() + margin)
    ax.set_zlim(verts[:, 2].min() - margin, verts[:, 2].max() + margin)
    ax.set_xlabel("X [m]")
    ax.set_ylabel("Y [m]")
    ax.set_zlabel("Z [m]")
    ax.set_title(title)

    wp_x = [verts[:, 0].min() - margin, verts[:, 0].max() + margin,
            verts[:, 0].max() + margin, verts[:, 0].min() - margin]
    wp_y = [verts[:, 1].min() - margin, verts[:, 1].min() - margin,
            verts[:, 1].max() + margin, verts[:, 1].max() + margin]
    wp_z = [0, 0, 0, 0]
    wp = Poly3DCollection(
        [list(zip(wp_x, wp_y, wp_z))],
        alpha=0.08, facecolor="cyan", edgecolor="steelblue", linewidth=0.5,
    )
    ax.add_collection3d(wp)

    try:
        ax.set_aspect("equal")
    except NotImplementedError:
        pass

    plt.tight_layout()
    plt.show()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description="Run Capytaine BEM for Wigley hull")
    ap.add_argument("--quick", action="store_true",
                    help="Reduced resolution for quick testing")
    ap.add_argument("--n-freq", type=int, default=None,
                    help="Number of frequency points (default: 200, quick: 30)")
    ap.add_argument("--freq-min", type=float, default=0.05,
                    help="Minimum angular frequency [rad/s]")
    ap.add_argument("--freq-max", type=float, default=3.0,
                    help="Maximum angular frequency [rad/s]")
    ap.add_argument("--irf-t-end", type=float, default=60.0,
                    help="IRF time range [s]")
    ap.add_argument("--irf-dt", type=float, default=0.05,
                    help="IRF time step [s]")
    ap.add_argument("--output", type=Path, default=None,
                    help="Output H5 file path")
    ap.add_argument("--meshes-dir", type=Path, default=None,
                    help="Directory containing .nemoh mesh")
    ap.add_argument("--jobs", "-j", type=int, default=-1,
                    help="Parallel workers for BEM solve (-1 = all cores)")
    ap.add_argument("--show", action="store_true",
                    help="Show the mesh and exit (no BEM solve)")
    ap.add_argument("--from-nc", type=Path, default=None,
                    help="Skip BEM solve; load saved .nc and re-run post-processing")
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent
    meshes_dir = args.meshes_dir or script_dir / "meshes"
    output = args.output or script_dir / "hydroData" / "wigley.h5"
    output.parent.mkdir(parents=True, exist_ok=True)
    nc_path = output.parent / "wigley_capytaine.nc"

    print("=" * 60)
    print("Wigley Hull BEM Analysis")
    print("=" * 60)

    print("\nLoading mesh...")
    body = load_body(meshes_dir)

    if args.show:
        _plot_mesh_matplotlib(body)
        return

    print("\nComputing hydrostatics from mesh...")
    body_hydrostatics = compute_body_hydrostatics(body)

    if args.from_nc:
        dataset = _load_nc(args.from_nc)
    else:
        n_freq = args.n_freq
        if n_freq is None:
            n_freq = 30 if args.quick else 200

        freq_range = np.linspace(args.freq_min, args.freq_max, n_freq)
        wave_directions = np.array([0.0])

        print("\nRunning BEM...")
        dataset = solve_bem(body, freq_range, wave_directions, n_jobs=args.jobs)

        print("\nSaving Capytaine NetCDF (checkpoint)...")
        try:
            _save_nc(dataset, nc_path)
        except Exception as e:
            print(f"  WARNING: NetCDF export failed: {e}")

    print("\nPost-processing and writing H5...")
    write_bemio_h5(output, dataset,
                   body_hydrostatics=body_hydrostatics,
                   irf_t_end=args.irf_t_end, irf_dt=args.irf_dt)

    print("\nDone.")


if __name__ == "__main__":
    main()
