# macOS install-time fixup: make bin/run_seastack and every bundled lib/*.dylib relocatable.
# Run via install(SCRIPT) after all runtime libraries are staged (cmake --install and CPack staging).
#
# install(TARGETS ... RUNTIME_DEPENDENCIES) copies third-party dylibs but leaves their install names,
# inter-library references and LC_RPATHs pointing at the build machine (Chrono build tree, Homebrew,
# VSG prefix). This script rewrites them to @rpath/<name>, resolved through the executable's
# @loader_path/../lib, removes absolute rpaths and ad-hoc re-signs modified files.
#
# Deliberately strict: any dependency that cannot be mapped to exactly one file inside the package
# aborts the install instead of being guessed. Do not add new bundling here to make it pass.
#
# Input: SEASTACK_FIXUP_REQUIRE_MOLTENVK (ON when VSG is enabled; set by a preceding install(CODE)).

set(_fx_prefix "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}")
set(_fx_lib "${_fx_prefix}/lib")
set(_fx_exe "${_fx_prefix}/bin/run_seastack")

function(_fx_fail msg)
    message(FATAL_ERROR "macOS bundle fixup: ${msg}")
endfunction()

function(_fx_run)
    execute_process(COMMAND ${ARGN}
        RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(NOT _res EQUAL 0)
        string(REPLACE ";" " " _cmd "${ARGN}")
        _fx_fail("command failed (${_res}): ${_cmd}\n${_out}${_err}")
    endif()
endfunction()

# True if <path> exists and its real path lies inside the package lib/ directory.
function(_fx_resolves_in_lib path out_var)
    set(${out_var} FALSE PARENT_SCOPE)
    if(EXISTS "${path}")
        file(REAL_PATH "${path}" _real)
        file(REAL_PATH "${_fx_lib}" _lib_real)
        string(FIND "${_real}" "${_lib_real}/" _pos)
        if(_pos EQUAL 0)
            set(${out_var} TRUE PARENT_SCOPE)
        endif()
    endif()
endfunction()

# Parse `otool -l`: install name, dylib dependencies (all LC_*_DYLIB load variants) and rpaths.
function(_fx_load_commands file out_id out_deps out_rpaths)
    execute_process(COMMAND /usr/bin/otool -l "${file}"
        RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(NOT _res EQUAL 0)
        _fx_fail("otool -l failed for ${file}: ${_err}")
    endif()
    string(REPLACE "\n" ";" _lines "${_out}")
    set(_cmd "")
    set(_id "")
    set(_deps "")
    set(_rpaths "")
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "^ +cmd (LC_[A-Z_]+)$")
            set(_cmd "${CMAKE_MATCH_1}")
        elseif(_line MATCHES "^ +name (.+) \\(offset [0-9]+\\)$")
            set(_name "${CMAKE_MATCH_1}")
            if(_cmd STREQUAL "LC_ID_DYLIB")
                set(_id "${_name}")
            elseif(_cmd MATCHES "^LC_(LOAD|LOAD_WEAK|REEXPORT|LAZY_LOAD|LOAD_UPWARD)_DYLIB$")
                list(APPEND _deps "${_name}")
            endif()
        elseif(_line MATCHES "^ +path (.+) \\(offset [0-9]+\\)$" AND _cmd STREQUAL "LC_RPATH")
            list(APPEND _rpaths "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _deps)
    set(${out_id} "${_id}" PARENT_SCOPE)
    set(${out_deps} "${_deps}" PARENT_SCOPE)
    set(${out_rpaths} "${_rpaths}" PARENT_SCOPE)
endfunction()

if(NOT EXISTS "${_fx_exe}")
    _fx_fail("${_fx_exe} not found")
endif()

if(SEASTACK_FIXUP_REQUIRE_MOLTENVK)
    if(NOT EXISTS "${_fx_lib}/libMoltenVK.dylib")
        _fx_fail("VSG is enabled but lib/libMoltenVK.dylib is not staged; the GUI cannot run on a clean Mac")
    endif()
    if(NOT EXISTS "${_fx_prefix}/share/vulkan/icd.d/MoltenVK_icd.json")
        _fx_fail("VSG is enabled but share/vulkan/icd.d/MoltenVK_icd.json is not staged")
    endif()
endif()

file(GLOB _fx_candidates LIST_DIRECTORIES false "${_fx_lib}/*.dylib")
set(_fx_files "${_fx_exe}")
foreach(_f IN LISTS _fx_candidates)
    if(NOT IS_SYMLINK "${_f}")
        list(APPEND _fx_files "${_f}")
    endif()
endforeach()

# Pass 1: build the rewrite plan and reject anything unresolved or ambiguous before changing files.
set(_fx_seen_bases "")
foreach(_f IN LISTS _fx_files)
    _fx_load_commands("${_f}" _id _deps _rpaths)
    get_filename_component(_fdir "${_f}" DIRECTORY)
    set(_changes "")

    if(NOT _f STREQUAL _fx_exe)
        if(_id STREQUAL "")
            _fx_fail("${_f} has no LC_ID_DYLIB")
        endif()
        get_filename_component(_id_base "${_id}" NAME)
        _fx_resolves_in_lib("${_fx_lib}/${_id_base}" _ok)
        if(NOT _ok)
            _fx_fail("${_f}: install name ${_id} does not match any file or symlink in lib/")
        endif()
        file(REAL_PATH "${_fx_lib}/${_id_base}" _id_real)
        file(REAL_PATH "${_f}" _f_real)
        if(NOT _id_real STREQUAL _f_real)
            _fx_fail("${_f}: install name ${_id} resolves to a different file (${_id_real})")
        endif()
    endif()

    foreach(_dep IN LISTS _deps)
        if(_dep MATCHES "^/usr/lib/" OR _dep MATCHES "^/System/Library/")
            continue()
        elseif(_dep MATCHES "^@rpath/(.+)$")
            _fx_resolves_in_lib("${_fx_lib}/${CMAKE_MATCH_1}" _ok)
            if(NOT _ok)
                _fx_fail("${_f}: dependency ${_dep} is not bundled in lib/")
            endif()
        elseif(_dep MATCHES "^@loader_path/(.+)$")
            _fx_resolves_in_lib("${_fdir}/${CMAKE_MATCH_1}" _ok)
            if(NOT _ok)
                _fx_fail("${_f}: dependency ${_dep} does not resolve inside lib/")
            endif()
        elseif(_dep MATCHES "^@executable_path/(.+)$")
            _fx_resolves_in_lib("${_fx_prefix}/bin/${CMAKE_MATCH_1}" _ok)
            if(NOT _ok)
                _fx_fail("${_f}: dependency ${_dep} does not resolve inside lib/")
            endif()
        elseif(_dep MATCHES "^/")
            get_filename_component(_base "${_dep}" NAME)
            _fx_resolves_in_lib("${_fx_lib}/${_base}" _ok)
            if(NOT _ok)
                _fx_fail("${_f}: absolute dependency ${_dep} is not bundled in lib/")
            endif()
            # Two different source paths with one basename must be the same file on this machine.
            string(MAKE_C_IDENTIFIER "${_base}" _key)
            if(DEFINED _fx_src_${_key} AND NOT _fx_src_${_key} STREQUAL _dep)
                set(_other "${_fx_src_${_key}}")
                if(NOT EXISTS "${_dep}" OR NOT EXISTS "${_other}")
                    _fx_fail("ambiguous dependency ${_base}: ${_other} and ${_dep}")
                endif()
                file(REAL_PATH "${_dep}" _r1)
                file(REAL_PATH "${_other}" _r2)
                if(NOT _r1 STREQUAL _r2)
                    _fx_fail("ambiguous dependency ${_base}: ${_other} -> ${_r2}, ${_dep} -> ${_r1}")
                endif()
            else()
                set(_fx_src_${_key} "${_dep}")
            endif()
            list(APPEND _changes -change "${_dep}" "@rpath/${_base}")
        else()
            _fx_fail("${_f}: unsupported dependency form ${_dep}")
        endif()
    endforeach()

    if(NOT _f STREQUAL _fx_exe AND NOT _id STREQUAL "@rpath/${_id_base}")
        list(APPEND _changes -id "@rpath/${_id_base}")
    endif()

    set(_bad_rpaths "")
    foreach(_rp IN LISTS _rpaths)
        if(NOT _rp MATCHES "^@")
            list(APPEND _bad_rpaths "${_rp}")
        endif()
    endforeach()

    string(MAKE_C_IDENTIFIER "${_f}" _fkey)
    set(_fx_changes_${_fkey} "${_changes}")
    set(_fx_rpaths_${_fkey} "${_bad_rpaths}")
endforeach()

# Pass 2: apply, strip absolute rpaths one occurrence at a time, re-sign what changed.
foreach(_f IN LISTS _fx_files)
    string(MAKE_C_IDENTIFIER "${_f}" _fkey)
    set(_changes "${_fx_changes_${_fkey}}")
    set(_bad_rpaths "${_fx_rpaths_${_fkey}}")
    if(NOT _changes AND NOT _bad_rpaths)
        continue()
    endif()
    if(_changes)
        _fx_run(/usr/bin/install_name_tool ${_changes} "${_f}")
    endif()
    foreach(_rp IN LISTS _bad_rpaths)
        _fx_run(/usr/bin/install_name_tool -delete_rpath "${_rp}" "${_f}")
    endforeach()
    _fx_load_commands("${_f}" _id _deps _rpaths)
    foreach(_rp IN LISTS _rpaths)
        if(NOT _rp MATCHES "^@")
            _fx_fail("${_f}: absolute rpath ${_rp} still present after fixup")
        endif()
    endforeach()
    _fx_run(/usr/bin/codesign --force --sign - "${_f}")
endforeach()

foreach(_f IN LISTS _fx_files)
    _fx_run(/usr/bin/codesign --verify --strict "${_f}")
endforeach()

list(LENGTH _fx_files _fx_count)
message(STATUS "macOS bundle fixup: ${_fx_count} Mach-O files relocatable and signed")
